name: Staging Deployment

on:
  push:
    branches:
      - release/**

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install
      
      # Ensure permissions for htmlhint and stylelint binaries
      - run: chmod +x ./node_modules/.bin/htmlhint
      - run: chmod +x ./node_modules/.bin/stylelint

      # Lint HTML and CSS using local binaries
      - run: ./node_modules/.bin/htmlhint "src/**/*.html"
      - run: ./node_modules/.bin/stylelint "src/**/*.css"
      - run: npx htmlhint src/
      - run: npx stylelint "**/*.css"
      - run: npx parcel build src/index.html --dist-dir staging-dist

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./staging-dist
          destination_dir: staging
